# Generated by Django 4.1 on 2022-08-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WithPet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
